# Generated by Django 4.0.4 on 2022-05-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_alter_newsletter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
